### ISSUE TITLE
Choose appropriate names for normalized num and denom

### ISSUE THREAD

**Issue by klaeufer** [LoyolaChicagoCode/scala-tdd-fundamentals#1]
https://github.com/LoyolaChicagoCode/scala-tdd-fundamentals/blob/master/src/main/scala/Rational.scala#L38

Pedagogically and stylistically, _n and _d are bad choices. I suggest numerator and denominator or n and d (after renaming the constructor arguments, which you have private anyway).

**Comment by gkthiruvathukal** [comment]
I absolutely agree with this, but these names were changed simply for the purpose of dealing with Sphinx formatting, which we are now not using. I may actually go back to what was there before (numerator and denominator, respectively).

Technically, however, I don't think these names are in any way a violation of Scala style but agree with your point in general, especially on pedagogical grounds.

**Comment by klaeufer** [comment]
OK, good. Btw, names with underscores _are_ "heavily" discouraged.

http://docs.scala-lang.org/style/naming-conventions.html

I think this is especially important with public members. We'll work on this at a suitable time.

**Comment by klaeufer** [comment]
Now the argument names are inconsistent with each other and with those of apply. Consider using n and d for them in both places (but keep the full names for the normalized values).

https://github.com/LoyolaChicagoCode/scala-tdd-fundamentals/blob/master/src/main/scala/Rational.scala#L33

**Comment by gkthiruvathukal** [comment]
Yes, I had completely forgotten to deal with the companion object. I'm kind of leaning toward n and d as well, because it makes formatting a bit less unwieldy. Thanks for catching this!
